#!/bin/bash
clear
echo "========================================================"
echo "       STATUSLINE OSC 8 LINK REGRESSION TEST            "
echo "========================================================"
echo ""
echo "TEST STEPS:"
echo ""
echo "  1. Run: claude"
echo ""
echo "  2. Look at the statusline at the bottom of the terminal"
echo "     - Find the 'uuid' text"
echo ""
echo "  3. Try to Ctrl+click the uuid link"
echo "     - WORKING: Text is underlined, click copies to clipboard"
echo "     - BROKEN:  No underline, clicking does nothing"
echo ""
echo "  4. Verify clipboard contents:"
echo "     xclip -selection clipboard -o"
echo ""
echo "========================================================"
echo ""
echo "Claude Code version: $(claude --version 2>/dev/null || echo 'not installed')"
echo ""
exec bash
